import { festivalImages, pujaImages } from './visualAssets';

export const pujaCatalog = [
  {
    id: 'ganesh-puja',
    title: 'Ganesh Puja',
    shortTitle: 'Ganesh Puja',
    price: '₹1,499',
    duration: '1 - 2 Hours',
    people: '1 - 11',
    bestFor: 'New Beginnings',
    image: pujaImages.ganesh,
    rating: 4.8,
    reviewCount: 124,
    category: 'Festival',
    budget: '₹1,000 - ₹2,000',
    about: 'Lord Ganesha is the remover of obstacles and the god of wisdom and prosperity. Performing this puja brings success in all endeavours.',
    benefits: ['Removes obstacles and challenges', 'Brings prosperity and good fortune', 'Best for new beginnings', 'Enhances wisdom and intellect'],
    samagri: ['Mango leaves', 'Modak', 'Flower garland', 'Aarti items', 'Sandal paste'],
    faq: ['What does Ganesh Puja help with? It removes obstacles and begins new work on a positive note.', 'Is the puja suitable for home? Yes, it can be done at home, office, or a temple setting.'],
    packages: [
      {
        name: 'Basic Package',
        price: '₹1,499',
        items: ['Essential Samagri', 'Standard Flowers', 'Basic Decoration', 'Puja Vidhi Booklet', 'Prasad'],
      },
      {
        name: 'Premium Package',
        price: '₹2,499',
        items: ['All Basic Package Items', 'Premium Flowers', 'Premium Decoration', 'Puja Vidhi Booklet', 'Prasad (Premium)', 'Puja Video Recording'],
      },
    ],
  },
  {
    id: 'satyanarayan-puja',
    title: 'Satyanarayan Puja',
    shortTitle: 'Satyanarayan Puja',
    price: '₹1,799',
    duration: '1 - 2 Hours',
    people: '1 - 11',
    bestFor: 'Family Blessings',
    image: pujaImages.satyanarayan,
    rating: 4.7,
    reviewCount: 98,
    category: 'Family',
    budget: '₹1,000 - ₹2,000',
    about: 'Satyanarayan Puja is widely performed to invoke peace, gratitude, and abundance. It is a spiritual ritual that strengthens family harmony and fulfilment.',
    benefits: ['Strengthens family unity', 'Invokes peace and gratitude', 'Brings prosperity and wellness', 'Suitable for special occasions'],
    samagri: ['Rice grains', 'Flowers', 'Fruits', 'Agarbatti', 'Panchamrit'],
    faq: ['Can it be performed on auspicious days? Yes, it is often scheduled on Purnima, festivals, and family occasions.', 'Do we need prior preparation? A few household items and a clean prayer space are enough.'],
    packages: [
      { name: 'Basic Package', price: '₹1,799', items: ['Essential Samagri', 'Flowers', 'Decoration', 'Pandit Ji Guidance'] },
      { name: 'Premium Package', price: '₹2,799', items: ['All Basic Package Items', 'Premium Decor', 'Recording', 'Special Aarti'] },
    ],
  },
  {
    id: 'navgraha-puja',
    title: 'Navgraha Puja',
    shortTitle: 'Navgraha Shanti',
    price: '₹3,200',
    duration: '3 - 5 Hours',
    people: '1 - 11',
    bestFor: 'Planetary Remedies',
    image: pujaImages.navgraha,
    rating: 4.9,
    reviewCount: 71,
    category: 'Remedy',
    budget: '₹3,000 - ₹4,500',
    about: 'Navgraha Shanti balances the nine planets and helps remove karmic obstacles affecting health, wealth, and stability.',
    benefits: ['Helps with planetary imbalance', 'Supports peace and stability', 'Ideal for major life transitions', 'Recommended for spiritual wellness'],
    samagri: ['Kalash', 'Flowers', 'Saffron', 'Rice', 'Hawan items'],
    faq: ['Who can opt for this puja? Anyone facing recurring hardship or wanting a spiritual reset can book it.', 'How long does it take? Usually 3 to 5 hours depending on the ritual structure.'],
    packages: [
      { name: 'Basic Package', price: '₹3,200', items: ['Navgraha Samagri', 'Basic Decors', 'Puja Booklet'] },
      { name: 'Premium Package', price: '₹4,800', items: ['All Basic Package Items', 'Premium Havan Material', 'Dedicated Aarti', 'Video Recording'] },
    ],
  },
  {
    id: 'griha-pravesh-puja',
    title: 'Griha Pravesh Puja',
    shortTitle: 'Griha Pravesh Puja',
    price: '₹2,499',
    duration: '2 - 3 Hours',
    people: '1 - 11',
    bestFor: 'Housewarming',
    image: pujaImages.grihaPravesh,
    rating: 4.8,
    reviewCount: 86,
    category: 'Housewarming',
    budget: '₹2,000 - ₹3,000',
    about: 'Griha Pravesh Puja is performed to bless a new home with positive energy, harmony, and divine protection.',
    benefits: ['Blesses new homes', 'Invokes peace and prosperity', 'Ideal for housewarming rituals', 'Helps establish positive energy'],
    samagri: ['Kalash', 'Flowers', 'Rice', 'Incense', 'Blessing thread'],
    faq: ['Is this suited for a new apartment? Yes, it is highly suitable for apartments, villas, and homes.', 'Can it be booked with a family? Yes, family participation is welcomed.'],
    packages: [
      { name: 'Basic Package', price: '₹2,499', items: ['Essential Samagri', 'Decoration', 'Puja Vidhi'] },
      { name: 'Premium Package', price: '₹3,799', items: ['All Basic Package Items', 'Premium Flowers', 'Aarti and Blessing Ceremony'] },
    ],
  },
  {
    id: 'rudrabhishek',
    title: 'Rudrabhishek',
    shortTitle: 'Rudrabhishek',
    price: '₹1,799',
    duration: '1 - 2 Hours',
    people: '1 - 11',
    bestFor: 'Spiritual Protection',
    image: festivalImages.ganeshChaturthi,
    rating: 4.6,
    reviewCount: 62,
    category: 'Temple',
    budget: '₹1,000 - ₹2,000',
    about: 'Rudrabhishek is a powerful act of devotion dedicated to Shiva, promoting inner strength, peace, and spiritual protection.',
    benefits: ['Spiritual grounding', 'Protection and peace', 'Supports concentration and calm', 'Ideal for family rituals'],
    samagri: ['Shivling items', 'Bilva leaves', 'Milk', 'Honey', 'Flowers'],
    faq: ['Can it be done at home? Yes, it can be arranged at home with a proper setup.', 'How long is the ceremony? Usually 1 to 2 hours.'],
    packages: [
      { name: 'Basic Package', price: '₹1,799', items: ['Essential Samagri', 'Standard Flower Setup'] },
      { name: 'Premium Package', price: '₹2,599', items: ['All Basic Package Items', 'Premium Decor', 'Recording'] },
    ],
  },
  {
    id: 'sundarkand-path',
    title: 'Sundarkand Path',
    shortTitle: 'Sundarkand Path',
    price: '₹1,599',
    duration: '1 - 2 Hours',
    people: '1 - 11',
    bestFor: 'Peace & Protection',
    image: festivalImages.diwali,
    rating: 4.5,
    reviewCount: 53,
    category: 'Path',
    budget: '₹1,000 - ₹2,000',
    about: 'Sundarkand Path is a devotional recitation believed to bring calm, courage, and protection from negative energy.',
    benefits: ['Creates a peaceful ambiance', 'Supports confidence and courage', 'Ideal for family worship', 'Suitable for spiritual routines'],
    samagri: ['Sundarkand book', 'Flower tray', 'Incense', 'Aarti items'],
    faq: ['Can I book it for a housewarming event? Yes, it is often included for additional blessing and calmness.', 'Do I need a special installation? No, a clean prayer area is enough.'],
    packages: [
      { name: 'Basic Package', price: '₹1,599', items: ['Recitation Booklet', 'Standard Decor'] },
      { name: 'Premium Package', price: '₹2,299', items: ['All Basic Package Items', 'Premium Aarti Setup', 'Audio Recording'] },
    ],
  },
];
